package day31.exceptiondemo;

import java.util.Scanner;

public class ExceptionDemo1 {

	public static void main(String[] args) {
//		int[]arr= new int[]{4,5,6};
//		arr[3]=40;
//		for(int i=0;i<=arr.length;i++)
//			System.out.println(arr[i]);
//	Scanner input=new Scanner(System.in);
//	System.out.println("Enter a:");
//	int a= input.nextInt();
//	System.out.println("Enter b:");
//	int b= input.nextInt();
//	int div=a/b;
//	System.out.println("Division is:"+div);
//	
//	String s1="";
//	char c=s1.charAt(2);
//	System.out.println(c);
	
//	String s2=null;
//	System.out.println(s2.toLowerCase());
//	FileInputStream fis=new FileInputStream("")	
		String n ="45a";
		int nn =Integer.parseInt(n);
		System.out.println(nn);

	}

}
// try => block => {}
//catch=>block => {}
//finally=>block=> {}
// throws=> clause (adding)
//throw=>statement

